### ISSUE TITLE
R&D100 logos

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/About-Us#16]
Is there a way to add the R&D100 logos to our github home page?  I added a blurb on the 'news and highlights' wiki. The logos are located here: 
https://github.com/CICE-Consortium/About-Us/wiki/images/RD100_2021_Gold_Logo.png
https://github.com/CICE-Consortium/About-Us/wiki/images/RD100_2021_Winner_Logo.png

**Comment by eclare108213** [comment]
I'd prefer to keep the other repos "clean" but can see the benefits of adding them.

**Comment by eclare108213** [comment]
maybe put them in the wiki rather than the code repo

**Comment by apcraig** [comment]
I like the wiki idea.  Will work on that.
