### ISSUE TITLE
copyright update

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/About-Us#7]
We need to update the year from 2019 to 2020 everywhere it appears in a copyright statement.  Is there a way to do this all at once using a slick script?  @apcraig I'd appreciate it if you'd at least locate all of them.  I would like to make sure that we have them in all the places needed, e.g. in the Icepack interface modules/routines.  I'm labeling this as "bug" because we haven't made the regular labels in this repository and it's high priority -- this needs to be done before the next release.

**Comment by apcraig** [comment]
I just checked out and reviewed the About-Us repo and the About-Us wiki and cannot find any copyright information.  There is copyright information in the CICE and Icepack repositories and documentation.  There is a bullet point in the release plans to check copyrights.  

I think we can close this for now.  If it needs to be reopened, please do so.

**Comment by eclare108213** [comment]
Thank you for checking!
